<package format="3">
  <name>gridmap_2d</name>
  <version>0.4.1</version>
  <description>
    gridmap_2d - a simple 2D gridmap structure, based on OpenCV's cv::Mat
  </description>
  <maintainer email="HornungA@informatik.uni-freiburg.de">Armin Hornung</maintainer>
  <maintainer email="aravindadp@gmail.com">Pramuditha Aravinda</maintainer>
  <license>BSD</license>
  <url type="website">http://ros.org/wiki/gridmap_2d</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>libopencv-dev</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>