<package format="3">
  <name>humanoid_planner_2d</name>
  <version>0.4.1</version>
  <description>
    humanoid_planner_2d - provides a simple 2D path planner as wrapper around
    SBPL (ARA*, AD*, R*).
  </description>
  <maintainer email="HornungA@informatik.uni-freiburg.de">Armin Hornung</maintainer>
  <maintainer email="aravindadp@gmail.com">Pramuditha Aravinda</maintainer>
  <author>Armin Hornung</author>
  <license>BSD</license>
  <url type="website">http://ros.org/wiki/humanoid_planner_2d</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>gridmap_2d</depend>
  <depend>nav_msgs</depend>
  <depend>sbpl</depend>
  <depend>visualization_msgs</depend>
  <depend>opencv4</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>