<?xml version="1.0"?>
<package format="3">
  <name>bascorro_demo</name>
  <version>0.0.0</version>
  <description>The bascorro_demo package</description>

  <maintainer email="alfretz@todo.todo">alfretz</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>robotis_controller_msgs</depend>
  <depend>op3_walking_module_msgs</depend>
  <depend>op3_action_module_msgs</depend>
  <depend>robotis_math</depend>
  <depend>op3_ball_detector</depend>
  <depend>boost</depend>
  <depend>eigen</depend>
  <depend>yaml-cpp</depend>
  <exec_depend>op3_manager</exec_depend>
  <exec_depend>op3_camera_setting_tool</exec_depend>
  <exec_depend>op3_web_setting_tool</exec_depend>
  <exec_depend>ros_madplay_player</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>